#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SPYDER - Autonomous Options Trading System

Spyder Version: 1.0
Module: SpyderY01_MarketSenseAgent.py
Group: Y (AutoAgents)
Purpose: 24/7 market awareness — maintains a living mental model of the market

Author: Mohamed Talib
Date Created: 2026-02-25
Last Updated: 2026-02-25 Time: 12:00:00

Description:
    Runs continuously across all market sessions. Synthesizes quantitative
    signals (HMM regime, GARCH volatility, VIX term structure, GEX/DEX levels)
    into coherent market narratives using a local LLM.

    Pre-market:  Gap analysis, overnight futures, global session review
    Market hours: Real-time regime monitoring, volume anomalies, level tracking
    Post-market:  EOD summary, key level calculation, earnings reaction analysis
    Overnight:    Macro event monitoring, correlation analysis, scenario planning

    Wraps the on-demand SpyderX13_MarketAnalysisAgent with autonomous scheduling,
    persistent state, and LLM-powered narrative synthesis.

License: All dependencies are MIT/BSD/Apache — AGPL-free.
"""

# ==============================================================================
# STANDARD IMPORTS
# ==============================================================================
import logging
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Set

# ==============================================================================
# THIRD-PARTY IMPORTS
# ==============================================================================
try:
    import numpy as np
    NUMPY_AVAILABLE = True
except ImportError:
    NUMPY_AVAILABLE = False

# ==============================================================================
# SPYDER IMPORTS
# ==============================================================================
from .SpyderY00_BaseAutoAgent import (
    BaseAutoAgent,
    AgentOutput,
    LLMRole,
    MarketSession,
)

try:
    from Spyder.SpyderX_Agents.SpyderX13_MarketAnalysisAgent import (
        SpyderX13_MarketAnalysisAgent,
    )
    X13_AVAILABLE = True
except ImportError:
    X13_AVAILABLE = False

try:
    from Spyder.SpyderE_Risk.SpyderE12_HMMRegimeDetector import (
        SpyderE12_HMMRegimeDetector,
    )
    HMM_AVAILABLE = True
except ImportError:
    HMM_AVAILABLE = False

try:
    from Spyder.SpyderF_Analysis.SpyderF10_MarketRegimeDetector import (
        SpyderF10_MarketRegimeDetector,
    )
    GARCH_AVAILABLE = True
except ImportError:
    GARCH_AVAILABLE = False


# ==============================================================================
# DATA STRUCTURES
# ==============================================================================
@dataclass
class MarketSnapshot:
    """Point-in-time market state captured by the agent."""
    timestamp: datetime = field(default_factory=datetime.now)
    session: str = ""
    regime: str = "unknown"
    regime_confidence: float = 0.0
    vix: float = 0.0
    vix_term_structure: str = "unknown"  # contango | backwardation | flat
    spy_price: float = 0.0
    spy_change_pct: float = 0.0
    volume_ratio: float = 1.0           # vs 20-day average
    gex_level: float = 0.0
    dex_level: float = 0.0
    key_support: float = 0.0
    key_resistance: float = 0.0
    narrative: str = ""                  # LLM-generated summary


@dataclass
class DailyBrief:
    """End-of-day market brief generated by the agent."""
    date: str = ""
    open_price: float = 0.0
    close_price: float = 0.0
    high: float = 0.0
    low: float = 0.0
    volume: int = 0
    regime_start: str = ""
    regime_end: str = ""
    regime_transitions: int = 0
    key_events: List[str] = field(default_factory=list)
    next_day_levels: Dict[str, float] = field(default_factory=dict)
    narrative: str = ""


# ==============================================================================
# MARKET SENSE AGENT
# ==============================================================================
class SpyderY01_MarketSenseAgent(BaseAutoAgent):
    """24/7 autonomous market awareness agent.

    Maintains a living mental model of the market by continuously monitoring
    regime state, vol dynamics, key levels, and macro context. Uses a local
    LLM to synthesize quantitative signals into human-readable narratives.

    Publishes to:
        market.regime      — Current regime with confidence
        market.analysis    — Full market analysis snapshot
        market.levels      — Support/resistance/GEX flip levels
        market.brief       — End-of-day summary (post-market)
    """

    AGENT_ID = "Y01_market_sense"
    AGENT_NAME = "MarketSense Agent"
    AGENT_VERSION = "1.0.0"
    DESCRIPTION = "24/7 market awareness with regime synthesis and narrative generation"

    # Active during ALL sessions
    ACTIVE_SESSIONS = {
        MarketSession.OVERNIGHT,
        MarketSession.PRE_MARKET,
        MarketSession.MARKET_OPEN,
        MarketSession.MARKET_HOURS,
        MarketSession.POWER_HOUR,
        MarketSession.POST_MARKET,
    }

    # Tick intervals by session (seconds)
    TICK_INTERVALS = {
        MarketSession.OVERNIGHT: 300,     # Every 5 min overnight
        MarketSession.PRE_MARKET: 120,    # Every 2 min pre-market
        MarketSession.MARKET_OPEN: 30,    # Every 30s at open
        MarketSession.MARKET_HOURS: 60,   # Every 1 min during market
        MarketSession.POWER_HOUR: 30,     # Every 30s power hour
        MarketSession.POST_MARKET: 180,   # Every 3 min post-market
    }

    TICK_INTERVAL = 60.0  # Default fallback

    # How many snapshots to keep in memory
    MAX_SNAPSHOT_HISTORY = 500

    def __init__(self, **kwargs: Any):
        super().__init__(**kwargs)

        # Internal state
        self._current_regime: str = "unknown"
        self._regime_confidence: float = 0.0
        self._snapshots: deque = deque(maxlen=self.MAX_SNAPSHOT_HISTORY)
        self._daily_briefs: List[Dict[str, Any]] = []
        self._last_regime_change: Optional[datetime] = None
        self._regime_history: List[Dict[str, Any]] = []
        self._tick_count: int = 0
        self._daily_brief_sent: bool = False

        # X-agent delegate (on-demand, stateless)
        self._x13_agent: Optional[Any] = None
        if X13_AVAILABLE:
            try:
                self._x13_agent = SpyderX13_MarketAnalysisAgent()
            except Exception:
                pass

    # ==========================================================================
    # LIFECYCLE HOOKS
    # ==========================================================================
    def on_start(self) -> None:
        """Subscribe to relevant topics and initialize delegates."""
        self.subscribe("market.data")
        self.subscribe("signals.regime")

    def on_wake(self, session: MarketSession) -> None:
        """Adjust tick interval when waking for a new session."""
        self.TICK_INTERVAL = self.TICK_INTERVALS.get(session, 60.0)
        super().on_wake(session)

    # ==========================================================================
    # MAIN TICK
    # ==========================================================================
    def tick(self, session: MarketSession) -> None:
        """Main work method — runs every tick interval.

        Session-aware behavior:
          - PRE_MARKET: Gap analysis + overnight summary
          - MARKET_OPEN: High-frequency regime monitoring
          - MARKET_HOURS: Standard regime + level tracking
          - POWER_HOUR: End-of-day positioning analysis
          - POST_MARKET: Generate daily brief
          - OVERNIGHT: Macro monitoring, correlation analysis
        """
        self._tick_count += 1

        # Adjust tick rate for current session
        self.TICK_INTERVAL = self.TICK_INTERVALS.get(session, 60.0)

        # Build current snapshot
        snapshot = self._build_snapshot(session)

        # Detect regime changes
        if snapshot.regime != self._current_regime and snapshot.regime != "unknown":
            self._handle_regime_change(snapshot)

        # Store snapshot
        self._snapshots.append(snapshot)

        # Generate LLM narrative periodically (not every tick)
        if self._tick_count % 5 == 0 or session == MarketSession.MARKET_OPEN:
            snapshot.narrative = self._generate_narrative(snapshot, session)

        # Publish outputs
        self._publish_regime(snapshot)
        self._publish_analysis(snapshot)

        # Post-market: generate daily brief once
        if session == MarketSession.POST_MARKET and not self._daily_brief_sent:
            self._generate_daily_brief()
            self._daily_brief_sent = True
        elif session != MarketSession.POST_MARKET:
            self._daily_brief_sent = False

    # ==========================================================================
    # SNAPSHOT BUILDING
    # ==========================================================================
    def _build_snapshot(self, session: MarketSession) -> MarketSnapshot:
        """Construct current market state from available data sources."""
        snapshot = MarketSnapshot(
            session=session.value,
        )

        # Try to get regime from HMM detector
        if HMM_AVAILABLE:
            try:
                detector = SpyderE12_HMMRegimeDetector()
                prediction = detector.predict_regime()
                if prediction:
                    snapshot.regime = getattr(prediction, "regime", "unknown")
                    snapshot.regime_confidence = getattr(
                        prediction, "confidence", 0.0
                    )
            except Exception:
                pass

        # Try to get regime from GARCH detector as secondary signal
        if GARCH_AVAILABLE and snapshot.regime == "unknown":
            try:
                detector = SpyderF10_MarketRegimeDetector()
                result = detector.detect_regime()
                if result:
                    snapshot.regime = str(getattr(result, "regime", "unknown"))
                    snapshot.regime_confidence = getattr(
                        result, "confidence", 0.0
                    )
            except Exception:
                pass

        # Try to get full analysis from X13
        if self._x13_agent:
            try:
                import asyncio
                loop = asyncio.new_event_loop()
                analysis = loop.run_until_complete(
                    self._x13_agent.analyze_market(symbol="SPY")
                )
                loop.close()
                if analysis:
                    snapshot.spy_price = getattr(analysis, "current_price", 0.0)
                    snapshot.spy_change_pct = getattr(analysis, "change_pct", 0.0)
            except Exception:
                pass

        return snapshot

    def _handle_regime_change(self, snapshot: MarketSnapshot) -> None:
        """Process a regime transition."""
        old_regime = self._current_regime
        self._current_regime = snapshot.regime
        self._regime_confidence = snapshot.regime_confidence
        self._last_regime_change = datetime.now()

        transition = {
            "from": old_regime,
            "to": snapshot.regime,
            "confidence": snapshot.regime_confidence,
            "timestamp": datetime.now().isoformat(),
        }
        self._regime_history.append(transition)

        # LLM analysis of the transition
        reasoning = self.llm_query(
            prompt=(
                f"Market regime just changed from '{old_regime}' to '{snapshot.regime}' "
                f"with {snapshot.regime_confidence:.0%} confidence. "
                f"VIX is at {snapshot.vix:.1f}. SPY is at ${snapshot.spy_price:.2f}. "
                f"What does this transition mean for SPY options strategies? "
                f"Be concise (3-4 sentences)."
            ),
            role=LLMRole.FINANCE,
            system_prompt=(
                "You are a quantitative trading analyst specializing in SPY options. "
                "Provide actionable insights about market regime transitions."
            ),
        )

        # Publish regime change alert
        self.publish(AgentOutput(
            agent_id=self.AGENT_ID,
            output_type="alert",
            topic="market.regime",
            payload=transition,
            confidence=snapshot.regime_confidence,
            reasoning=reasoning or f"Regime changed: {old_regime} → {snapshot.regime}",
            priority="HIGH",
            ttl_seconds=600,
        ))

    # ==========================================================================
    # NARRATIVE GENERATION
    # ==========================================================================
    def _generate_narrative(
        self, snapshot: MarketSnapshot, session: MarketSession
    ) -> str:
        """Use the local LLM to generate a market narrative."""
        # Build context from recent snapshots
        recent_regimes = [
            s.regime for s in list(self._snapshots)[-10:]
        ]
        regime_stability = (
            len(set(recent_regimes)) == 1 if recent_regimes else False
        )

        prompt = (
            f"Current market state ({session.value} session):\n"
            f"- Regime: {snapshot.regime} (confidence: {snapshot.regime_confidence:.0%})\n"
            f"- SPY: ${snapshot.spy_price:.2f} ({snapshot.spy_change_pct:+.2f}%)\n"
            f"- VIX: {snapshot.vix:.1f} (term structure: {snapshot.vix_term_structure})\n"
            f"- Volume ratio: {snapshot.volume_ratio:.2f}x average\n"
            f"- GEX: {snapshot.gex_level:.0f} | DEX: {snapshot.dex_level:.0f}\n"
            f"- Key support: ${snapshot.key_support:.2f} | Resistance: ${snapshot.key_resistance:.2f}\n"
            f"- Regime stable: {'Yes' if regime_stability else 'No (changing)'}\n\n"
            f"Provide a 3-sentence market summary with actionable implication for "
            f"SPY options trading."
        )

        return self.llm_query(
            prompt=prompt,
            role=LLMRole.FAST,
            system_prompt=(
                "You are a concise market analyst for an automated SPY options system. "
                "Summarize market conditions and state the primary trading implication."
            ),
        ) or ""

    # ==========================================================================
    # DAILY BRIEF
    # ==========================================================================
    def _generate_daily_brief(self) -> None:
        """Generate end-of-day summary using snapshots and LLM."""
        today_snapshots = [
            s for s in self._snapshots
            if s.timestamp.date() == datetime.now().date()
        ]

        if not today_snapshots:
            return

        # Collect stats from today's snapshots
        regimes_seen = [s.regime for s in today_snapshots if s.regime != "unknown"]
        transitions = 0
        for i in range(1, len(regimes_seen)):
            if regimes_seen[i] != regimes_seen[i - 1]:
                transitions += 1

        brief = DailyBrief(
            date=datetime.now().strftime("%Y-%m-%d"),
            regime_start=regimes_seen[0] if regimes_seen else "unknown",
            regime_end=regimes_seen[-1] if regimes_seen else "unknown",
            regime_transitions=transitions,
        )

        # Generate narrative
        prompt = (
            f"End-of-day summary for {brief.date}:\n"
            f"- Regime: started as '{brief.regime_start}', ended as '{brief.regime_end}'\n"
            f"- Regime transitions today: {transitions}\n"
            f"- Total snapshots: {len(today_snapshots)}\n\n"
            f"Write a brief end-of-day market summary (4-5 sentences) covering:\n"
            f"1. How the day unfolded\n"
            f"2. Key regime dynamics\n"
            f"3. What to watch for tomorrow\n"
            f"4. Recommended overnight positioning bias"
        )

        brief.narrative = self.llm_query(
            prompt=prompt,
            role=LLMRole.PRIMARY,
            system_prompt=(
                "You are a senior options trading strategist writing an end-of-day "
                "brief for an automated SPY options trading system."
            ),
        ) or "Daily brief generation unavailable."

        brief_dict = {
            "date": brief.date,
            "regime_start": brief.regime_start,
            "regime_end": brief.regime_end,
            "regime_transitions": brief.regime_transitions,
            "narrative": brief.narrative,
        }
        self._daily_briefs.append(brief_dict)

        self.publish(AgentOutput(
            agent_id=self.AGENT_ID,
            output_type="report",
            topic="market.brief",
            payload=brief_dict,
            confidence=0.8,
            reasoning=brief.narrative,
            priority="NORMAL",
            ttl_seconds=86400,  # 24 hours
        ))

    # ==========================================================================
    # PUBLISHING
    # ==========================================================================
    def _publish_regime(self, snapshot: MarketSnapshot) -> None:
        """Publish current regime state."""
        self.publish(AgentOutput(
            agent_id=self.AGENT_ID,
            output_type="analysis",
            topic="market.regime",
            payload={
                "regime": snapshot.regime,
                "confidence": snapshot.regime_confidence,
                "session": snapshot.session,
                "timestamp": snapshot.timestamp.isoformat(),
            },
            confidence=snapshot.regime_confidence,
            reasoning=f"Current regime: {snapshot.regime}",
            priority="NORMAL",
        ))

    def _publish_analysis(self, snapshot: MarketSnapshot) -> None:
        """Publish full market analysis."""
        self.publish(AgentOutput(
            agent_id=self.AGENT_ID,
            output_type="analysis",
            topic="market.analysis",
            payload={
                "regime": snapshot.regime,
                "regime_confidence": snapshot.regime_confidence,
                "spy_price": snapshot.spy_price,
                "spy_change_pct": snapshot.spy_change_pct,
                "vix": snapshot.vix,
                "vix_term_structure": snapshot.vix_term_structure,
                "volume_ratio": snapshot.volume_ratio,
                "gex_level": snapshot.gex_level,
                "key_support": snapshot.key_support,
                "key_resistance": snapshot.key_resistance,
                "narrative": snapshot.narrative,
                "session": snapshot.session,
                "timestamp": snapshot.timestamp.isoformat(),
            },
            confidence=snapshot.regime_confidence,
            reasoning=snapshot.narrative or f"Market analysis: {snapshot.regime}",
            priority="LOW",
        ))

    # ==========================================================================
    # STATE PERSISTENCE
    # ==========================================================================
    def get_state_snapshot(self) -> Dict[str, Any]:
        """Return state for disk persistence."""
        return {
            "current_regime": self._current_regime,
            "regime_confidence": self._regime_confidence,
            "tick_count": self._tick_count,
            "regime_history": self._regime_history[-50:],  # Last 50 transitions
            "daily_briefs": self._daily_briefs[-30:],      # Last 30 days
        }

    def restore_state(self, state: Dict[str, Any]) -> None:
        """Restore state from disk."""
        self._current_regime = state.get("current_regime", "unknown")
        self._regime_confidence = state.get("regime_confidence", 0.0)
        self._tick_count = state.get("tick_count", 0)
        self._regime_history = state.get("regime_history", [])
        self._daily_briefs = state.get("daily_briefs", [])


# ==============================================================================
# FACTORY
# ==============================================================================
def create_market_sense_agent(**kwargs: Any) -> SpyderY01_MarketSenseAgent:
    """Factory function for creating the MarketSense agent."""
    return SpyderY01_MarketSenseAgent(**kwargs)
