#!/bin/bash
# ==============================================================================
# SPYDER - Remote TWS Setup Script
# ==============================================================================
# This script helps configure Spyder to connect to TWS running on a separate
# Windows computer, following the distributed architecture pattern recommended
# for professional algorithmic trading systems.
# ==============================================================================

set -e  # Exit on any error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"

echo -e "${BLUE}╔══════════════════════════════════════════════════════════════════════════════╗"
echo -e "║                      SPYDER REMOTE TWS SETUP                                ║"
echo -e "║              Professional Distributed Trading Architecture                   ║"
echo -e "╚══════════════════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# ==============================================================================
# FUNCTIONS
# ==============================================================================

show_help() {
    echo -e "${GREEN}Usage: $0 [OPTIONS]${NC}"
    echo ""
    echo "Options:"
    echo "  -h, --help              Show this help message"
    echo "  -i, --interactive       Interactive configuration mode"
    echo "  -t, --test-connection   Test connection to remote TWS"
    echo "  -r, --revert            Revert to local Gateway configuration"
    echo "  --windows-ip IP         Set Windows computer IP address"
    echo "  --paper-port PORT       Set paper trading port (default: 7497)"
    echo "  --live-port PORT        Set live trading port (default: 7496)"
    echo ""
    echo "Examples:"
    echo "  $0 --interactive                    # Interactive setup"
    echo "  $0 --windows-ip 192.168.1.100      # Quick setup with IP"
    echo "  $0 --test-connection               # Test existing configuration"
    echo ""
}

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if IP address is valid
validate_ip() {
    local ip=$1
    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        IFS='.' read -ra ADDR <<< "$ip"
        for i in "${ADDR[@]}"; do
            if [[ $i -gt 255 ]]; then
                return 1
            fi
        done
        return 0
    fi
    return 1
}

# Test network connectivity to Windows machine
test_network_connectivity() {
    local ip=$1
    local port=$2

    log_info "Testing network connectivity to $ip:$port..."

    # Test ping first
    if ping -c 1 -W 3 "$ip" > /dev/null 2>&1; then
        log_success "Network connectivity to $ip: OK"
    else
        log_warning "Ping to $ip failed - but this might be normal (Windows firewall)"
    fi

    # Test port connectivity
    if timeout 5 bash -c "cat < /dev/null > /dev/tcp/$ip/$port" 2>/dev/null; then
        log_success "Port $port is accessible on $ip"
        return 0
    else
        log_error "Port $port is NOT accessible on $ip"
        log_info "Make sure TWS is running and API is enabled on the Windows computer"
        return 1
    fi
}

# Backup current configuration
backup_config() {
    local timestamp=$(date +"%Y%m%d_%H%M%S")
    local backup_dir="$CONFIG_DIR/backups"

    mkdir -p "$backup_dir"

    if [ -f "$CONFIG_DIR/config.py" ]; then
        cp "$CONFIG_DIR/config.py" "$backup_dir/config_${timestamp}.py"
        log_success "Configuration backed up to: $backup_dir/config_${timestamp}.py"
    fi
}

# Create remote TWS configuration
create_remote_config() {
    local windows_ip=$1
    local paper_port=${2:-7497}
    local live_port=${3:-7496}

    log_info "Creating remote TWS configuration..."

    # Backup existing config
    backup_config

    # Create new configuration
    cat > "$CONFIG_DIR/config_remote_tws.py" << EOF
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SPYDER - Remote TWS Configuration
Generated by setup_remote_tws.sh on $(date)
Windows TWS Computer: $windows_ip
Paper Port: $paper_port | Live Port: $live_port
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ==============================================================================
# REMOTE TWS CONFIGURATION
# ==============================================================================
IB_CONFIG = {
    "use_gateway": False,  # Using TWS instead of Gateway
    "connection_type": "remote_tws",  # Track connection type
    "windows_computer": {
        "ip_address": "$windows_ip",
        "hostname": "Windows-TWS-Computer",
        "setup_date": "$(date)",
    },
    "gateway": {
        "paper": {
            "host": "$windows_ip",  # Windows computer IP
            "port": $paper_port,    # TWS Paper port (default 7497)
            "clientId": 1,
        },
        "live": {
            "host": "$windows_ip",  # Windows computer IP
            "port": $live_port,     # TWS Live port (default 7496)
            "clientId": 2,
        },
    },
}

# ==============================================================================
# CONNECTION RELIABILITY SETTINGS
# ==============================================================================
REMOTE_CONNECTION_CONFIG = {
    "connection_timeout": 30,      # Increased for network latency
    "reconnection_attempts": 5,    # More attempts for network issues
    "reconnection_delay": 10,      # Longer delay between attempts
    "heartbeat_interval": 30,      # Monitor connection health
    "network_timeout": 45,         # Network operation timeout
    "enable_connection_pooling": True,  # Use your proven pooling system
}

# ==============================================================================
# NETWORK DIAGNOSTICS
# ==============================================================================
NETWORK_DIAGNOSTICS = {
    "ping_test_enabled": True,
    "port_check_enabled": True,
    "latency_monitoring": True,
    "connection_quality_alerts": True,
}

# ==============================================================================
# TRADING CONFIGURATION (unchanged from original)
# ==============================================================================
TRADING_CONFIG = {
    # Position Limits
    "risk_limits": {
        "max_position_size": 10000,
        "max_contracts_per_trade": 10,
        "max_daily_loss": 500,
        "max_daily_trades": 20,
        "max_open_positions": 5,
    },
    # Trading Hours (Eastern Time)
    "trading_hours": {
        "pre_market_start": "08:00",
        "market_open": "09:30",
        "market_close": "16:00",
        "after_hours_end": "17:00",
        "timezone": "US/Eastern",
    },
    # SPY Options Specific Settings
    "spy_options": {
        "min_days_to_expiry": 0,
        "max_days_to_expiry": 45,
        "min_option_volume": 100,
        "min_open_interest": 50,
        "strike_range_percent": 2.0,
        "preferred_expiries": ["0DTE", "1DTE", "Weekly", "Monthly"],
    },
    # Strategy Selection
    "active_strategies": [
        "iron_condor",
        "credit_spread",
        "zero_dte_scalping",
    ],
    # Execution Settings
    "execution": {
        "order_type": "LMT",
        "price_offset_ticks": 1,
        "max_slippage_percent": 0.5,
        "fill_wait_seconds": 30,
        "use_adaptive_orders": True,
    },
    # Risk Management
    "risk_management": {
        "stop_loss_percent": 50,
        "profit_target_percent": 25,
        "trailing_stop_percent": 10,
        "max_loss_per_trade": 200,
        "use_portfolio_hedging": True,
    },
    # Notifications (enhanced for remote setup)
    "notifications": {
        "telegram_alerts": bool(os.environ.get("TELEGRAM_BOT_TOKEN", "")),
        "telegram_bot_token": os.environ.get("TELEGRAM_BOT_TOKEN", ""),
        "telegram_chat_id": os.environ.get("TELEGRAM_CHAT_ID", ""),
        "email_alerts": bool(os.environ.get("EMAIL_ADDRESS", "")),
        "email_address": os.environ.get("EMAIL_ADDRESS", ""),
        "email_password": os.environ.get("EMAIL_PASSWORD", ""),
        "smtp_server": os.environ.get("SMTP_SERVER", "smtp.gmail.com"),
        "smtp_port": int(os.environ.get("SMTP_PORT", "587")),
        # Enhanced alerts for remote setup
        "alert_on_trade_fill": True,
        "alert_on_stop_loss": True,
        "alert_on_daily_summary": True,
        "alert_on_errors": True,
        "alert_on_large_moves": True,
        "alert_on_connection_issues": True,  # New: Network issues
        "alert_on_windows_computer_down": True,  # New: Remote computer down
    },
}

# ==============================================================================
# STRATEGY CONFIGURATIONS (unchanged)
# ==============================================================================
STRATEGY_CONFIG = {
    "iron_condor": {
        "enabled": True,
        "delta_short": 0.15,
        "delta_long": 0.05,
        "min_credit": 0.30,
        "days_to_expiry": [0, 1, 2],
        "entry_time": "10:00",
        "exit_time": "15:30",
        "max_loss_percent": 200,
    },
    "credit_spread": {
        "enabled": True,
        "spread_width": 5,
        "delta_short": 0.20,
        "min_credit": 0.25,
        "trade_direction": "both",
        "entry_conditions": {
            "min_iv_rank": 30,
            "rsi_oversold": 30,
            "rsi_overbought": 70,
        },
    },
    "zero_dte_scalping": {
        "enabled": True,
        "entry_window": ["09:45", "11:00"],
        "scalp_target": 0.10,
        "max_contracts": 5,
        "momentum_period": 5,
        "min_volume": 500,
        "use_limit_orders": True,
    },
}

# ==============================================================================
# DATABASE AND LOGGING (unchanged)
# ==============================================================================
DATABASE_CONFIG = {
    "db_path": "data/spyder.db",
    "backup_enabled": True,
    "backup_interval_hours": 24,
    "backup_retention_days": 30,
}

LOGGING_CONFIG = {
    "log_level": os.environ.get("LOG_LEVEL", "INFO"),
    "log_to_file": True,
    "log_file_path": "logs/spyder_remote_tws.log",  # Different log file
    "log_rotation": "daily",
    "log_retention_days": 30,
    "log_format": "%(asctime)s - %(name)s - %(levelname)s - [REMOTE-TWS] %(message)s",
}

SYSTEM_CONFIG = {
    "mode": (
        "production"
        if os.environ.get("DEBUG_MODE", "False").lower() == "false"
        else "development"
    ),
    "debug": os.environ.get("DEBUG_MODE", "False").lower() == "true",
    "performance_monitoring": True,
    "health_check_interval": 300,
    "auto_restart_on_error": False,
    "max_memory_usage_mb": 2048,
    "remote_tws_monitoring": True,  # New: Monitor remote connection
}

# ==============================================================================
# HELPER FUNCTIONS FOR REMOTE TWS
# ==============================================================================
def get_active_config():
    """Get configuration for active trading mode with remote TWS settings"""
    # For remote TWS, we don't need auth credentials in the same way
    # TWS handles authentication on the Windows computer

    paper_config = IB_CONFIG["gateway"]["paper"]
    live_config = IB_CONFIG["gateway"]["live"]

    # Default to paper for initial setup
    mode = os.environ.get("TRADING_MODE", "paper")

    if mode == "paper":
        return {
            "host": paper_config["host"],
            "port": paper_config["port"],
            "clientId": paper_config["clientId"],
            "mode": "paper",
            "connection_type": "remote_tws",
            "remote_ip": "$windows_ip",
        }
    else:
        return {
            "host": live_config["host"],
            "port": live_config["port"],
            "clientId": live_config["clientId"],
            "mode": "live",
            "connection_type": "remote_tws",
            "remote_ip": "$windows_ip",
        }

def validate_remote_connection():
    """Validate remote TWS connection"""
    import socket
    import time

    config = get_active_config()
    host = config["host"]
    port = config["port"]

    try:
        # Test TCP connectivity
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(10)
        result = sock.connect_ex((host, port))
        sock.close()

        if result == 0:
            return True, f"Connection to {host}:{port} successful"
        else:
            return False, f"Cannot connect to {host}:{port} (error: {result})"

    except Exception as e:
        return False, f"Connection test failed: {str(e)}"

# Print configuration status on import
if __name__ != "__main__":
    print("🔗 SPYDER Remote TWS Configuration Loaded")
    print(f"   Windows Computer: $windows_ip")
    print(f"   Paper Port: $paper_port | Live Port: $live_port")
    print(f"   Connection Type: remote_tws")

if __name__ == "__main__":
    # Test the configuration when run directly
    success, message = validate_remote_connection()
    print(f"Connection Test: {'✅' if success else '❌'} {message}")
EOF

    log_success "Remote TWS configuration created: $CONFIG_DIR/config_remote_tws.py"
}

# Test connection to remote TWS
test_remote_connection() {
    log_info "Testing connection to remote TWS..."

    # Source the configuration to get IP and ports
    if [ -f "$CONFIG_DIR/config_remote_tws.py" ]; then
        # Extract IP and ports from config file
        local windows_ip=$(grep 'ip_address.*:' "$CONFIG_DIR/config_remote_tws.py" | sed 's/.*: *"\([^"]*\)".*/\1/')
        local paper_port=$(grep 'port.*:.*#.*Paper' "$CONFIG_DIR/config_remote_tws.py" | grep -o '[0-9]*')
        local live_port=$(grep 'port.*:.*#.*Live' "$CONFIG_DIR/config_remote_tws.py" | grep -o '[0-9]*')

        if [ -n "$windows_ip" ] && [ -n "$paper_port" ]; then
            log_info "Testing connection to $windows_ip:$paper_port (paper trading)..."
            test_network_connectivity "$windows_ip" "$paper_port"
        else
            log_error "Could not extract connection details from configuration"
            return 1
        fi
    else
        log_error "Remote TWS configuration not found. Run setup first."
        return 1
    fi
}

# Interactive configuration mode
interactive_setup() {
    echo -e "${BLUE}╔══════════════════════════════════════════════════════════════════════════════╗"
    echo -e "║                        INTERACTIVE SETUP MODE                               ║"
    echo -e "╚══════════════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Get Windows computer IP
    while true; do
        echo -e "${YELLOW}Enter the IP address of your Windows computer running TWS:${NC}"
        echo -e "${BLUE}  (You can find this by running 'ipconfig' on Windows)${NC}"
        read -p "IP Address: " windows_ip

        if validate_ip "$windows_ip"; then
            log_success "Valid IP address: $windows_ip"
            break
        else
            log_error "Invalid IP address format. Please enter a valid IPv4 address."
        fi
    done

    # Get paper trading port
    echo ""
    echo -e "${YELLOW}Enter the paper trading port (default 7497 for TWS):${NC}"
    read -p "Paper Port [7497]: " paper_port
    paper_port=${paper_port:-7497}

    # Get live trading port
    echo ""
    echo -e "${YELLOW}Enter the live trading port (default 7496 for TWS):${NC}"
    read -p "Live Port [7496]: " live_port
    live_port=${live_port:-7496}

    # Test connectivity
    echo ""
    log_info "Testing connectivity to Windows computer..."
    if test_network_connectivity "$windows_ip" "$paper_port"; then
        log_success "Connection test passed!"
    else
        echo ""
        log_warning "Connection test failed. Common solutions:"
        echo -e "${BLUE}  1. Make sure TWS is running on Windows computer${NC}"
        echo -e "${BLUE}  2. Enable API in TWS: API -> Settings -> Enable ActiveX and Socket Clients${NC}"
        echo -e "${BLUE}  3. Add this Ubuntu computer's IP to TWS Trusted IPs${NC}"
        echo -e "${BLUE}  4. Check Windows firewall settings${NC}"
        echo ""

        while true; do
            read -p "Continue with setup anyway? (y/n): " continue_setup
            case $continue_setup in
                [Yy]* ) break;;
                [Nn]* )
                    log_info "Setup cancelled. Fix connection issues and try again."
                    exit 1
                    ;;
                * ) echo "Please answer yes or no.";;
            esac
        done
    fi

    # Create configuration
    echo ""
    log_info "Creating remote TWS configuration..."
    create_remote_config "$windows_ip" "$paper_port" "$live_port"

    # Offer to switch to new config
    echo ""
    while true; do
        read -p "Switch to the new remote TWS configuration now? (y/n): " switch_config
        case $switch_config in
            [Yy]* )
                switch_to_remote_config
                break
                ;;
            [Nn]* )
                log_info "Configuration created but not activated."
                log_info "Run '$0 --switch-to-remote' to activate later."
                break
                ;;
            * ) echo "Please answer yes or no.";;
        esac
    done

    show_next_steps
}

# Switch to remote configuration
switch_to_remote_config() {
    if [ -f "$CONFIG_DIR/config_remote_tws.py" ]; then
        # Backup current config
        backup_config

        # Switch to remote config
        cp "$CONFIG_DIR/config_remote_tws.py" "$CONFIG_DIR/config.py"
        log_success "Switched to remote TWS configuration"

        # Update any hardcoded localhost references in your codebase
        update_localhost_references
    else
        log_error "Remote TWS configuration not found. Run setup first."
        exit 1
    fi
}

# Update localhost references in codebase
update_localhost_references() {
    log_info "Updating localhost references in codebase..."

    # Get the Windows IP from config
    local windows_ip=$(grep 'ip_address.*:' "$CONFIG_DIR/config.py" | sed 's/.*: *"\([^"]*\)".*/\1/')

    if [ -n "$windows_ip" ]; then
        # Find and update common localhost references (but be conservative)
        log_info "Found Windows IP: $windows_ip"
        log_info "Note: Manual code updates may be needed for hardcoded '127.0.0.1' references"

        # Create a summary of files that might need updates
        echo ""
        log_warning "Files that may need manual updates:"
        grep -r "127\.0\.0\.1" --include="*.py" "$SCRIPT_DIR" | head -10 | while read line; do
            echo -e "${YELLOW}  $line${NC}"
        done
    fi
}

# Revert to local Gateway configuration
revert_to_local() {
    log_info "Reverting to local Gateway configuration..."

    if [ -f "$CONFIG_DIR/backups" ]; then
        # Find most recent backup
        local latest_backup=$(ls -t "$CONFIG_DIR/backups/config_"*.py 2>/dev/null | head -1)
        if [ -n "$latest_backup" ]; then
            cp "$latest_backup" "$CONFIG_DIR/config.py"
            log_success "Reverted to: $latest_backup"
        else
            log_error "No backup found. Please restore configuration manually."
        fi
    else
        log_error "No backup directory found. Cannot revert automatically."
    fi
}

# Show next steps
show_next_steps() {
    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════════════════════════════════╗"
    echo -e "║                             SETUP COMPLETE!                                 ║"
    echo -e "╚══════════════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Next Steps:${NC}"
    echo ""
    echo -e "${YELLOW}1. On Windows Computer:${NC}"
    echo -e "   ${BLUE}• Make sure TWS is running${NC}"
    echo -e "   ${BLUE}• Enable API: API -> Settings -> Enable ActiveX and Socket Clients${NC}"
    echo -e "   ${BLUE}• Add this computer's IP to Trusted IPs in TWS${NC}"
    echo -e "   ${BLUE}• Configure Windows Firewall to allow TWS ports${NC}"
    echo ""
    echo -e "${YELLOW}2. Test Connection:${NC}"
    echo -e "   ${BLUE}$0 --test-connection${NC}"
    echo ""
    echo -e "${YELLOW}3. Start Spyder Dashboard:${NC}"
    echo -e "   ${BLUE}./launch_dashboard_production.py${NC}"
    echo ""
    echo -e "${YELLOW}4. Monitor Logs:${NC}"
    echo -e "   ${BLUE}tail -f logs/spyder_remote_tws.log${NC}"
    echo ""
}

# ==============================================================================
# MAIN SCRIPT LOGIC
# ==============================================================================

# Parse command line arguments
INTERACTIVE=false
TEST_CONNECTION=false
REVERT=false
WINDOWS_IP=""
PAPER_PORT=""
LIVE_PORT=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -i|--interactive)
            INTERACTIVE=true
            shift
            ;;
        -t|--test-connection)
            TEST_CONNECTION=true
            shift
            ;;
        -r|--revert)
            REVERT=true
            shift
            ;;
        --windows-ip)
            WINDOWS_IP="$2"
            shift 2
            ;;
        --paper-port)
            PAPER_PORT="$2"
            shift 2
            ;;
        --live-port)
            LIVE_PORT="$2"
            shift 2
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Create config directory if it doesn't exist
mkdir -p "$CONFIG_DIR/backups"

# Execute based on arguments
if [ "$REVERT" = true ]; then
    revert_to_local
    exit 0
fi

if [ "$TEST_CONNECTION" = true ]; then
    test_remote_connection
    exit 0
fi

if [ "$INTERACTIVE" = true ]; then
    interactive_setup
    exit 0
fi

if [ -n "$WINDOWS_IP" ]; then
    # Quick setup mode
    if ! validate_ip "$WINDOWS_IP"; then
        log_error "Invalid IP address: $WINDOWS_IP"
        exit 1
    fi

    PAPER_PORT=${PAPER_PORT:-7497}
    LIVE_PORT=${LIVE_PORT:-7496}

    log_info "Quick setup mode:"
    log_info "  Windows IP: $WINDOWS_IP"
    log_info "  Paper Port: $PAPER_PORT"
    log_info "  Live Port: $LIVE_PORT"

    create_remote_config "$WINDOWS_IP" "$PAPER_PORT" "$LIVE_PORT"

    # Test connection
    if test_network_connectivity "$WINDOWS_IP" "$PAPER_PORT"; then
        log_success "Setup completed successfully!"
        switch_to_remote_config
        show_next_steps
    else
        log_warning "Setup completed but connection test failed."
        log_info "Configuration created but not activated."
        log_info "Fix connection issues and run: $0 --test-connection"
    fi
    exit 0
fi

# Default: show help and prompt for interactive mode
echo -e "${BLUE}SPYDER Remote TWS Setup${NC}"
echo ""
log_info "No arguments provided. Use one of these options:"
echo ""
show_help
echo ""
while true; do
    read -p "Would you like to run interactive setup now? (y/n): " run_interactive
    case $run_interactive in
        [Yy]* )
            interactive_setup
            break
            ;;
        [Nn]* )
            log_info "Setup cancelled. Run '$0 --help' for options."
            exit 0
            ;;
        * ) echo "Please answer yes or no.";;
    esac
done
