#!/bin/bash
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Script: SpyderQ01_Setup.sh
# Group: Q (Scripts/Shell)
# Purpose: Main installation and setup script for Spyder Gateway System
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Complete setup script that creates directory structure, installs
#     dependencies, sets up Python virtual environment, and generates all
#     necessary configuration files and helper scripts for the system.
# ===============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SPYDER_HOME="/home/adam/Projects/Spyder"
VENV_NAME="spyder_venv"
PYTHON_VERSION="python3.10"
IB_GATEWAY_PATH="$HOME/Jts"
LOG_DIR="$SPYDER_HOME/logs"
CONFIG_DIR="$SPYDER_HOME/config"
DATA_DIR="$SPYDER_HOME/data"
SCRIPTS_DIR="$SPYDER_HOME/SpyderQ_Scripts"

echo -e "${BLUE}================================================${NC}"
echo -e "${BLUE}  SPYDER Multi-Client Gateway Setup${NC}"
echo -e "${BLUE}  Script: SpyderQ01_Setup.sh${NC}"
echo -e "${BLUE}================================================${NC}"

# Function to print colored messages
print_msg() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

# Check if running on Ubuntu
if ! grep -q "Ubuntu" /etc/os-release; then
    print_error "This script is designed for Ubuntu. Detected: $(lsb_release -ds)"
    exit 1
fi

# Check Python version
print_msg "Checking Python version..."
if ! command -v $PYTHON_VERSION &> /dev/null; then
    print_error "Python 3.10 is required but not found."
    echo "Install with: sudo apt-get install python3.10 python3.10-venv python3.10-dev"
    exit 1
fi

# Create directory structure
print_msg "Creating directory structure..."
mkdir -p "$SPYDER_HOME"/{logs,config,data,scripts,services,tests,backup}
mkdir -p "$LOG_DIR"/{clients,system,trading}
mkdir -p "$DATA_DIR"/{reports,metrics,health}

# Create Python virtual environment
print_msg "Creating Python virtual environment..."
cd "$SPYDER_HOME"
if [ ! -d "$VENV_NAME" ]; then
    $PYTHON_VERSION -m venv $VENV_NAME
    print_msg "Virtual environment created"
else
    print_warning "Virtual environment already exists"
fi

# Activate virtual environment
source "$SPYDER_HOME/$VENV_NAME/bin/activate"

# Upgrade pip
print_msg "Upgrading pip..."
pip install --upgrade pip wheel setuptools

# Install Python dependencies
print_msg "Installing Python dependencies..."
cat > "$SPYDER_HOME/requirements.txt" << 'EOF'
# Core Trading Dependencies
ib_insync==0.9.86
pandas==2.0.3
numpy==1.24.3

# GUI Dependencies
PyQt6==6.5.0
PyQt6-Qt6==6.5.0
PyQt6-sip==13.5.1

# Monitoring & Metrics
prometheus-client==0.17.1
psutil==5.9.5
py-cpuinfo==9.0.0

# Database
sqlalchemy==2.0.19

# Utilities
pytz==2023.3
python-dotenv==1.0.0
pyyaml==6.0.1
requests==2.31.0
aiohttp==3.8.5
asyncio==3.4.3

# Logging
loguru==0.7.0
colorlog==6.7.0

# Testing
pytest==7.4.0
pytest-asyncio==0.21.1
pytest-qt==4.2.0
pytest-cov==4.1.0

# Development tools
black==23.7.0
pylint==2.17.4
mypy==1.4.1
EOF

pip install -r "$SPYDER_HOME/requirements.txt"

# Create .env template
print_msg "Creating environment configuration..."
cat > "$SPYDER_HOME/.env" << EOF
# SPYDER Configuration File
# Generated by SpyderQ01_Setup.sh

# IB Gateway Configuration
IB_USERNAME=your_username
IB_PASSWORD=your_password
TRADING_MODE=paper

# Gateway Settings
GATEWAY_HOST=127.0.0.1
GATEWAY_PORT_PAPER=4002
GATEWAY_PORT_LIVE=4001
GATEWAY_CLIENT_ID=0
GATEWAY_REGION=America

# System Settings
LOG_LEVEL=INFO
TIMEZONE=America/New_York

# Monitoring
PROMETHEUS_PORT=8000
METRICS_UPDATE_INTERVAL=10
HEALTH_CHECK_INTERVAL=30

# Paths
SPYDER_HOME=$SPYDER_HOME
IB_GATEWAY_PATH=$IB_GATEWAY_PATH
LOG_DIR=$LOG_DIR
DATA_DIR=$DATA_DIR
CONFIG_DIR=$CONFIG_DIR
EOF

print_warning "Please edit $SPYDER_HOME/.env with your IB credentials"

# ===============================================================================
# Create SpyderQ10_StartAll.sh
# ===============================================================================
cat > "$SCRIPTS_DIR/SpyderQ10_StartAll.sh" << 'EOF'
#!/bin/bash
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Script: SpyderQ10_StartAll.sh
# Group: Q (Scripts/Shell)
# Purpose: Start all Spyder Gateway components
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Starts all monitoring components in the correct order with proper
#     health checks. Ensures IB Gateway is running before starting monitors.
# ===============================================================================

SPYDER_HOME="/home/adam/Projects/Spyder"
source "$SPYDER_HOME/spyder_venv/bin/activate"
source "$SPYDER_HOME/.env"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "================================================"
echo "  SPYDER Gateway - Starting All Components"
echo "  Script: SpyderQ10_StartAll.sh"
echo "================================================"

# Check if IB Gateway is running
check_gateway() {
    if pgrep -f "ibgateway" > /dev/null || nc -z localhost ${GATEWAY_PORT_PAPER} 2>/dev/null; then
        echo -e "${GREEN}[✓]${NC} IB Gateway is running"
        return 0
    else
        echo -e "${RED}[✗]${NC} IB Gateway is not running"
        echo -e "${YELLOW}[!]${NC} Please start IB Gateway first"
        return 1
    fi
}

# Start Prometheus Metrics
start_metrics() {
    echo "Starting Prometheus Metrics (SpyderB15)..."
    cd "$SPYDER_HOME"
    python -m SpyderB_Broker.SpyderB15_PrometheusMetrics > "$LOG_DIR/system/metrics.log" 2>&1 &
    METRICS_PID=$!
    echo $METRICS_PID > "$LOG_DIR/metrics.pid"
    sleep 2
    if ps -p $METRICS_PID > /dev/null; then
        echo -e "${GREEN}[✓]${NC} Prometheus Metrics started (PID: $METRICS_PID)"
        return 0
    else
        echo -e "${RED}[✗]${NC} Failed to start Prometheus Metrics"
        return 1
    fi
}

# Start Watchdog
start_watchdog() {
    echo "Starting Multi-Client Watchdog (SpyderB14)..."
    cd "$SPYDER_HOME"
    python -m SpyderB_Broker.SpyderB14_MultiClientWatchdog > "$LOG_DIR/system/watchdog.log" 2>&1 &
    WATCHDOG_PID=$!
    echo $WATCHDOG_PID > "$LOG_DIR/watchdog.pid"
    sleep 3
    if ps -p $WATCHDOG_PID > /dev/null; then
        echo -e "${GREEN}[✓]${NC} Watchdog started (PID: $WATCHDOG_PID)"
        return 0
    else
        echo -e "${RED}[✗]${NC} Failed to start Watchdog"
        return 1
    fi
}

# Start Integration Manager
start_integration() {
    echo "Starting Integration Manager (SpyderB16)..."
    cd "$SPYDER_HOME"
    python -m SpyderB_Broker.SpyderB16_GatewayIntegration > "$LOG_DIR/system/integration.log" 2>&1 &
    INTEGRATION_PID=$!
    echo $INTEGRATION_PID > "$LOG_DIR/integration.pid"
    sleep 2
    if ps -p $INTEGRATION_PID > /dev/null; then
        echo -e "${GREEN}[✓]${NC} Integration Manager started (PID: $INTEGRATION_PID)"
        return 0
    else
        echo -e "${RED}[✗]${NC} Failed to start Integration Manager"
        return 1
    fi
}

# Main execution
if check_gateway; then
    echo ""
    echo "Starting components..."
    echo "------------------------"
    
    if start_metrics && start_watchdog && start_integration; then
        echo ""
        echo "================================================"
        echo -e "${GREEN}All components started successfully!${NC}"
        echo "================================================"
        echo "Prometheus Metrics: http://localhost:${PROMETHEUS_PORT}/metrics"
        echo "Logs Directory: $LOG_DIR"
        echo "Use 'SpyderQ20_Status.sh' to check status"
        echo "Use 'SpyderQ11_StopAll.sh' to stop all components"
    else
        echo ""
        echo -e "${RED}Some components failed to start${NC}"
        echo "Check logs in: $LOG_DIR/system/"
        exit 1
    fi
else
    exit 1
fi
EOF

chmod +x "$SCRIPTS_DIR/SpyderQ10_StartAll.sh"

# ===============================================================================
# Create SpyderQ11_StopAll.sh
# ===============================================================================
cat > "$SCRIPTS_DIR/SpyderQ11_StopAll.sh" << 'EOF'
#!/bin/bash
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Script: SpyderQ11_StopAll.sh
# Group: Q (Scripts/Shell)
# Purpose: Stop all Spyder Gateway components gracefully
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Stops all monitoring components in reverse order with proper cleanup.
#     Ensures graceful shutdown and removes PID files.
# ===============================================================================

SPYDER_HOME="/home/adam/Projects/Spyder"
LOG_DIR="$SPYDER_HOME/logs"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "================================================"
echo "  SPYDER Gateway - Stopping All Components"
echo "  Script: SpyderQ11_StopAll.sh"
echo "================================================"

stop_component() {
    local name=$1
    local pidfile=$2
    
    if [ -f "$pidfile" ]; then
        PID=$(cat "$pidfile")
        if ps -p $PID > /dev/null 2>&1; then
            echo "Stopping $name (PID: $PID)..."
            kill -TERM $PID 2>/dev/null
            sleep 2
            
            # Force kill if still running
            if ps -p $PID > /dev/null 2>&1; then
                echo -e "${YELLOW}[!]${NC} Force stopping $name"
                kill -KILL $PID 2>/dev/null
            fi
            
            echo -e "${GREEN}[✓]${NC} $name stopped"
            rm -f "$pidfile"
        else
            echo -e "${YELLOW}[!]${NC} $name not running (stale PID file)"
            rm -f "$pidfile"
        fi
    else
        echo -e "${YELLOW}[!]${NC} $name not running (no PID file)"
    fi
}

# Stop components in reverse order
echo ""
stop_component "Integration Manager" "$LOG_DIR/integration.pid"
stop_component "Multi-Client Watchdog" "$LOG_DIR/watchdog.pid"
stop_component "Prometheus Metrics" "$LOG_DIR/metrics.pid"

echo ""
echo "================================================"
echo -e "${GREEN}All components stopped${NC}"
echo "================================================"
EOF

chmod +x "$SCRIPTS_DIR/SpyderQ11_StopAll.sh"

# ===============================================================================
# Create SpyderQ20_Status.sh
# ===============================================================================
cat > "$SCRIPTS_DIR/SpyderQ20_Status.sh" << 'EOF'
#!/bin/bash
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Script: SpyderQ20_Status.sh
# Group: Q (Scripts/Shell)
# Purpose: Check status of all Spyder Gateway components
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Displays comprehensive status of all system components including
#     IB Gateway, monitoring services, ports, and system resources.
# ===============================================================================

SPYDER_HOME="/home/adam/Projects/Spyder"
LOG_DIR="$SPYDER_HOME/logs"
source "$SPYDER_HOME/.env" 2>/dev/null

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "================================================"
echo "  SPYDER Gateway System Status"
echo "  Script: SpyderQ20_Status.sh"
echo "  $(date '+%Y-%m-%d %H:%M:%S %Z')"
echo "================================================"

check_component() {
    local name=$1
    local pidfile=$2
    
    if [ -f "$pidfile" ]; then
        PID=$(cat "$pidfile")
        if ps -p $PID > /dev/null 2>&1; then
            # Get memory usage
            MEM=$(ps -o rss= -p $PID | awk '{printf "%.1f", $1/1024}')
            echo -e "${GREEN}[✓]${NC} $name (PID: $PID, Mem: ${MEM}MB)"
            return 0
        else
            echo -e "${RED}[✗]${NC} $name (stale PID)"
            return 1
        fi
    else
        echo -e "${RED}[✗]${NC} $name"
        return 1
    fi
}

echo ""
echo "Component Status:"
echo "-----------------"

# Check IB Gateway
if pgrep -f "ibgateway" > /dev/null; then
    GATEWAY_PID=$(pgrep -f "ibgateway" | head -1)
    echo -e "${GREEN}[✓]${NC} IB Gateway (PID: $GATEWAY_PID)"
else
    echo -e "${RED}[✗]${NC} IB Gateway"
fi

# Check components
check_component "Prometheus Metrics" "$LOG_DIR/metrics.pid"
check_component "Multi-Client Watchdog" "$LOG_DIR/watchdog.pid"
check_component "Integration Manager" "$LOG_DIR/integration.pid"

echo ""
echo "Network Ports:"
echo "--------------"

check_port() {
    local port=$1
    local name=$2
    if netstat -tuln 2>/dev/null | grep -q ":$port "; then
        echo -e "${GREEN}[✓]${NC} Port $port ($name)"
    else
        echo -e "${RED}[✗]${NC} Port $port ($name)"
    fi
}

check_port 4002 "IB Gateway API (Paper)"
check_port 4001 "IB Gateway API (Live)"
check_port 8000 "Prometheus Metrics"

echo ""
echo "System Resources:"
echo "-----------------"
echo "Memory: $(free -h | awk '/^Mem:/ {printf "%s / %s (%.1f%%)", $3, $2, $3/$2*100}')"
echo "CPU Load: $(uptime | awk -F'load average:' '{print $2}')"
echo "Disk Usage (${SPYDER_HOME}):"
du -sh "$SPYDER_HOME" 2>/dev/null | awk '{print "  Total: " $1}'
du -sh "$LOG_DIR" 2>/dev/null | awk '{print "  Logs: " $1}'
du -sh "$DATA_DIR" 2>/dev/null | awk '{print "  Data: " $1}'

echo ""
echo "Recent Errors (last 5):"
echo "-----------------------"
if [ -d "$LOG_DIR" ]; then
    ERRORS=$(grep -i "error\|critical" "$LOG_DIR/system/"*.log 2>/dev/null | tail -5)
    if [ -n "$ERRORS" ]; then
        echo "$ERRORS" | while IFS= read -r line; do
            echo "  ${line##*/}"
        done
    else
        echo "  No recent errors"
    fi
else
    echo "  Log directory not found"
fi

echo ""
echo "Client Health Check:"
echo "--------------------"
if curl -s localhost:8000/metrics > /dev/null 2>&1; then
    echo -e "${GREEN}[✓]${NC} Metrics endpoint responding"
    # Get client connection status
    curl -s localhost:8000/metrics | grep "ib_client_connected" | grep -v "#" | head -9 | while read line; do
        if [[ $line =~ client_id=\"([0-9])\" ]]; then
            CLIENT_ID="${BASH_REMATCH[1]}"
            if [[ $line =~ \}\ ([0-9.]+)$ ]]; then
                STATUS="${BASH_REMATCH[1]}"
                if [ "$STATUS" = "1" ]; then
                    echo -e "  ${GREEN}[✓]${NC} Client $CLIENT_ID connected"
                else
                    echo -e "  ${RED}[✗]${NC} Client $CLIENT_ID disconnected"
                fi
            fi
        fi
    done
else
    echo -e "${RED}[✗]${NC} Metrics endpoint not responding"
fi

echo ""
echo "================================================"
EOF

chmod +x "$SCRIPTS_DIR/SpyderQ20_Status.sh"

# ===============================================================================
# Create SpyderQ21_Monitor.sh
# ===============================================================================
cat > "$SCRIPTS_DIR/SpyderQ21_Monitor.sh" << 'EOF'
#!/bin/bash
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Script: SpyderQ21_Monitor.sh
# Group: Q (Scripts/Shell)
# Purpose: Live monitoring of client connections and metrics
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Provides real-time monitoring display of all 9 client connections,
#     system health metrics, and performance indicators. Updates every 5 seconds.
# ===============================================================================

SPYDER_HOME="/home/adam/Projects/Spyder"
source "$SPYDER_HOME/spyder_venv/bin/activate" 2>/dev/null

echo "Starting SPYDER Live Monitor (SpyderQ21)"
echo "Press Ctrl+C to exit"
echo ""

watch -n 5 -c "
echo '================================================'
echo '     SPYDER Multi-Client Live Monitor'
echo '     $(date +\"%H:%M:%S\")'
echo '================================================'
echo ''
echo 'CLIENT CONNECTIONS:'
echo '-------------------'
curl -s localhost:8000/metrics 2>/dev/null | grep ib_client_connected | grep -v '#' | while read line; do
    if [[ \$line =~ client_id=\\\"([0-9])\\\" ]]; then
        CLIENT=\${BASH_REMATCH[1]}
        if [[ \$line =~ \}\ ([0-9.]+) ]]; then
            STATUS=\${BASH_REMATCH[1]}
            if [ \"\$STATUS\" = \"1\" ]; then
                printf '  ✓ Client %s: Connected\n' \$CLIENT
            else
                printf '  ✗ Client %s: Disconnected\n' \$CLIENT
            fi
        fi
    fi
done

echo ''
echo 'SYSTEM METRICS:'
echo '---------------'
curl -s localhost:8000/metrics 2>/dev/null | grep -E 'system_health_score|ib_gateway_health_score' | grep -v '#' | head -2

echo ''
echo 'API ACTIVITY:'
echo '-------------'
curl -s localhost:8000/metrics 2>/dev/null | grep -E 'ib_gateway_api_calls_total|ib_gateway_order_submissions_total' | grep -v '#' | tail -2

echo ''
echo 'SYSTEM RESOURCES:'
echo '-----------------'
echo \"Memory: \$(free -h | awk '/^Mem:/ {print \$3 \" / \" \$2}')\"
echo \"CPU: \$(top -bn1 | grep 'Cpu(s)' | awk '{print \$2}')%\"
echo '================================================'
"
EOF

chmod +x "$SCRIPTS_DIR/SpyderQ21_Monitor.sh"

# ===============================================================================
# Create SpyderQ30_TestDev.sh
# ===============================================================================
cat > "$SCRIPTS_DIR/SpyderQ30_TestDev.sh" << 'EOF'
#!/bin/bash
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Script: SpyderQ30_TestDev.sh
# Group: Q (Scripts/Shell)
# Purpose: Development testing and validation script
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Comprehensive testing script for development. Tests module imports,
#     configurations, mock connections, and runs unit tests if available.
# ===============================================================================

SPYDER_HOME="/home/adam/Projects/Spyder"
source "$SPYDER_HOME/spyder_venv/bin/activate"
cd "$SPYDER_HOME"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "================================================"
echo "  SPYDER Development Test Suite"
echo "  Script: SpyderQ30_TestDev.sh"
echo "================================================"

# Test individual modules
test_module() {
    local module=$1
    echo -n "  Testing $module... "
    if python -c "from SpyderB_Broker.$module import *" 2>/dev/null; then
        echo -e "${GREEN}✓${NC}"
        return 0
    else
        echo -e "${RED}✗${NC}"
        return 1
    fi
}

echo ""
echo "1. Module Import Tests:"
echo "-----------------------"
test_module "SpyderB13_GatewayConfig"
test_module "SpyderB14_MultiClientWatchdog"
test_module "SpyderB15_PrometheusMetrics"
test_module "SpyderB16_GatewayIntegration"

echo ""
echo "2. Configuration Tests:"
echo "-----------------------"
python << 'PYTHON_TEST'
try:
    from SpyderB_Broker.SpyderB13_GatewayConfig import GatewayConfig, get_client_allocation
    config = GatewayConfig()
    clients = get_client_allocation()
    print(f"  ✓ Config loaded: {config.trading_mode.value} mode")
    print(f"  ✓ Clients configured: {len(clients)} clients")
    print(f"  ✓ Timezone: {config.timezone}")
except Exception as e:
    print(f"  ✗ Configuration error: {e}")
PYTHON_TEST

echo ""
echo "3. Mock Connection Test:"
echo "------------------------"
python << 'PYTHON_TEST'
try:
    from unittest.mock import MagicMock
    mock_ib = MagicMock()
    mock_ib.isConnected.return_value = True
    print("  ✓ Mock IB client created")
    print(f"  ✓ Mock connection status: {mock_ib.isConnected()}")
except Exception as e:
    print(f"  ✗ Mock test error: {e}")
PYTHON_TEST

echo ""
echo "4. Health Check Test:"
echo "---------------------"
python << 'PYTHON_TEST'
import psutil
print(f"  ✓ CPU Usage: {psutil.cpu_percent(interval=1):.1f}%")
print(f"  ✓ Memory Usage: {psutil.virtual_memory().percent:.1f}%")
print(f"  ✓ Process Count: {len(psutil.pids())}")
PYTHON_TEST

echo ""
echo "5. Unit Tests:"
echo "--------------"
if [ -d "$SPYDER_HOME/tests" ]; then
    if command -v pytest &> /dev/null; then
        echo "Running pytest..."
        pytest "$SPYDER_HOME/tests" -v --tb=short --no-header 2>/dev/null || echo "  No tests found or test errors"
    else
        echo "  pytest not installed (pip install pytest)"
    fi
else
    echo "  No tests directory found"
fi

echo ""
echo "================================================"
echo -e "${GREEN}Test suite completed${NC}"
echo "================================================"
EOF

chmod +x "$SCRIPTS_DIR/SpyderQ30_TestDev.sh"

# ===============================================================================
# Create SpyderQ70_Watchdog.service
# ===============================================================================
cat > "$SPYDER_HOME/services/SpyderQ70_Watchdog.service" << EOF
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Service: SpyderQ70_Watchdog.service
# Group: Q (Scripts/Shell)
# Purpose: Systemd service for Multi-Client Watchdog
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Systemd service configuration for automatic startup of the Multi-Client
#     Watchdog component. Ensures monitoring starts on system boot.
# ===============================================================================

[Unit]
Description=SPYDER Multi-Client Watchdog Service
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
Group=$USER
WorkingDirectory=$SPYDER_HOME
Environment="PATH=$SPYDER_HOME/spyder_venv/bin:/usr/local/bin:/usr/bin:/bin"
Environment="PYTHONPATH=$SPYDER_HOME"
Environment="HOME=/home/$USER"
ExecStart=$SPYDER_HOME/spyder_venv/bin/python -m SpyderB_Broker.SpyderB14_MultiClientWatchdog
Restart=always
RestartSec=10
StandardOutput=append:$LOG_DIR/system/watchdog.log
StandardError=append:$LOG_DIR/system/watchdog_error.log

[Install]
WantedBy=multi-user.target
EOF

# ===============================================================================
# Create SpyderQ71_Metrics.service
# ===============================================================================
cat > "$SPYDER_HOME/services/SpyderQ71_Metrics.service" << EOF
# ===============================================================================
# SPYDER - Autonomous Options Trading System
#
# Service: SpyderQ71_Metrics.service
# Group: Q (Scripts/Shell)
# Purpose: Systemd service for Prometheus Metrics
# Author: Mohamed Talib
# Date Created: 2025-08-03
# Last Updated: 2025-08-03 Time: 15:30:00
#
# Description:
#     Systemd service configuration for Prometheus Metrics exporter.
#     Provides metrics endpoint for monitoring all 9 client connections.
# ===============================================================================

[Unit]
Description=SPYDER Prometheus Metrics Service
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
Group=$USER
WorkingDirectory=$SPYDER_HOME
Environment="PATH=$SPYDER_HOME/spyder_venv/bin:/usr/local/bin:/usr/bin:/bin"
Environment="PYTHONPATH=$SPYDER_HOME"
Environment="HOME=/home/$USER"
ExecStart=$SPYDER_HOME/spyder_venv/bin/python -m SpyderB_Broker.SpyderB15_PrometheusMetrics
Restart=always
RestartSec=10
StandardOutput=append:$LOG_DIR/system/metrics.log
StandardError=append:$LOG_DIR/system/metrics_error.log

[Install]
WantedBy=multi-user.target
EOF

# Create convenience aliases with new naming
print_msg "Creating convenience aliases..."
cat >> ~/.bashrc << 'EOF'

# SPYDER Gateway Aliases (Q-Scripts)
alias spyder-start='~/Spyder/scripts/SpyderQ10_StartAll.sh'
alias spyder-stop='~/Spyder/scripts/SpyderQ11_StopAll.sh'
alias spyder-restart='spyder-stop && sleep 2 && spyder-start'
alias spyder-status='~/Spyder/scripts/SpyderQ20_Status.sh'
alias spyder-monitor='~/Spyder/scripts/SpyderQ21_Monitor.sh'
alias spyder-test='~/Spyder/scripts/SpyderQ30_TestDev.sh'
alias spyder-logs='tail -f ~/Spyder/logs/system/*.log'
alias spyder-env='source ~/Spyder/spyder_venv/bin/activate && cd ~/Spyder'
alias spyder-config='nano ~/Spyder/.env'
EOF

# Create script index
print_msg "Creating script index..."
cat > "$SCRIPTS_DIR/INDEX.md" << 'EOF'
# SPYDER Q-Scripts Index

## Setup & Installation (Q00-Q09)
- **SpyderQ01_Setup.sh** - Main installation and setup script

## Start/Stop/Control (Q10-Q19)
- **SpyderQ10_StartAll.sh** - Start all monitoring components
- **SpyderQ11_StopAll.sh** - Stop all components gracefully

## Monitoring & Status (Q20-Q29)
- **SpyderQ20_Status.sh** - Check system status
- **SpyderQ21_Monitor.sh** - Live monitoring display

## Testing & Development (Q30-Q39)
- **SpyderQ30_TestDev.sh** - Development testing suite

## Service Files (Q70-Q79)
- **SpyderQ70_Watchdog.service** - Systemd service for Watchdog
- **SpyderQ71_Metrics.service** - Systemd service for Metrics

## Quick Commands
```bash
spyder-start    # Start all components
spyder-stop     # Stop all components
spyder-status   # Check status
spyder-monitor  # Live monitoring
spyder-test     # Run tests
```
EOF

# Final summary
echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}    Setup Complete with Q-Script Naming!${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""
echo "Scripts created in: $SCRIPTS_DIR/"
echo "  • SpyderQ01_Setup.sh        - Main setup (this script)"
echo "  • SpyderQ10_StartAll.sh     - Start all components"
echo "  • SpyderQ11_StopAll.sh      - Stop all components"
echo "  • SpyderQ20_Status.sh       - Check status"
echo "  • SpyderQ21_Monitor.sh      - Live monitoring"
echo "  • SpyderQ30_TestDev.sh      - Development tests"
echo ""
echo "Services created in: $SPYDER_HOME/services/"
echo "  • SpyderQ70_Watchdog.service"
echo "  • SpyderQ71_Metrics.service"
echo ""
echo "Next steps:"
echo "1. Edit configuration: nano $SPYDER_HOME/.env"
echo "2. Copy your Spyder modules to: $SPYDER_HOME/"
echo "3. Start IB Gateway"
echo "4. Run: spyder-start (or $SCRIPTS_DIR/SpyderQ10_StartAll.sh)"
echo ""
echo "To enable auto-start on boot:"
echo "  sudo cp $SPYDER_HOME/services/SpyderQ*.service /etc/systemd/system/"
echo "  sudo systemctl enable SpyderQ70_Watchdog.service"
echo "  sudo systemctl enable SpyderQ71_Metrics.service"
echo ""
echo -e "${YELLOW}Remember to: source ~/.bashrc${NC}"