#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SPYDER - Remote TWS Configuration
Generated by setup_remote_tws.sh on Fri Oct  3 11:51:12 PM WEST 2025
Windows TWS Computer: 192.168.1.244
Paper Port: 7497 | Live Port: 7496
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ==============================================================================
# REMOTE TWS CONFIGURATION
# ==============================================================================
IB_CONFIG = {
    "use_gateway": False,  # Using TWS instead of Gateway
    "connection_type": "remote_tws",  # Track connection type
    "windows_computer": {
        "ip_address": "192.168.1.4",
        "hostname": "Windows-TWS-Computer",
        "setup_date": "Fri Oct  3 11:51:12 PM WEST 2025",
    },
    "gateway": {
        "paper": {
            "host": "192.168.1.4",  # Windows computer IP
            "port": 7497,  # TWS Paper port (default 7497)
            "clientId": 1,
        },
        "live": {
            "host": "192.168.1.4",  # Windows computer IP
            "port": 7496,  # TWS Live port (default 7496)
            "clientId": 2,
        },
    },
}

# ==============================================================================
# CONNECTION RELIABILITY SETTINGS
# ==============================================================================
REMOTE_CONNECTION_CONFIG = {
    "connection_timeout": 30,  # Increased for network latency
    "reconnection_attempts": 5,  # More attempts for network issues
    "reconnection_delay": 10,  # Longer delay between attempts
    "heartbeat_interval": 30,  # Monitor connection health
    "network_timeout": 45,  # Network operation timeout
    "enable_connection_pooling": True,  # Use your proven pooling system
}

# ==============================================================================
# NETWORK DIAGNOSTICS
# ==============================================================================
NETWORK_DIAGNOSTICS = {
    "ping_test_enabled": True,
    "port_check_enabled": True,
    "latency_monitoring": True,
    "connection_quality_alerts": True,
}

# ==============================================================================
# TRADING CONFIGURATION (unchanged from original)
# ==============================================================================
TRADING_CONFIG = {
    # Position Limits
    "risk_limits": {
        "max_position_size": 10000,
        "max_contracts_per_trade": 10,
        "max_daily_loss": 500,
        "max_daily_trades": 20,
        "max_open_positions": 5,
    },
    # Trading Hours (Eastern Time)
    "trading_hours": {
        "pre_market_start": "08:00",
        "market_open": "09:30",
        "market_close": "16:00",
        "after_hours_end": "17:00",
        "timezone": "US/Eastern",
    },
    # SPY Options Specific Settings
    "spy_options": {
        "min_days_to_expiry": 0,
        "max_days_to_expiry": 45,
        "min_option_volume": 100,
        "min_open_interest": 50,
        "strike_range_percent": 2.0,
        "preferred_expiries": ["0DTE", "1DTE", "Weekly", "Monthly"],
    },
    # Strategy Selection
    "active_strategies": [
        "iron_condor",
        "credit_spread",
        "zero_dte_scalping",
    ],
    # Execution Settings
    "execution": {
        "order_type": "LMT",
        "price_offset_ticks": 1,
        "max_slippage_percent": 0.5,
        "fill_wait_seconds": 30,
        "use_adaptive_orders": True,
    },
    # Risk Management
    "risk_management": {
        "stop_loss_percent": 50,
        "profit_target_percent": 25,
        "trailing_stop_percent": 10,
        "max_loss_per_trade": 200,
        "use_portfolio_hedging": True,
    },
    # Notifications (enhanced for remote setup)
    "notifications": {
        "telegram_alerts": bool(os.environ.get("TELEGRAM_BOT_TOKEN", "")),
        "telegram_bot_token": os.environ.get("TELEGRAM_BOT_TOKEN", ""),
        "telegram_chat_id": os.environ.get("TELEGRAM_CHAT_ID", ""),
        "email_alerts": bool(os.environ.get("EMAIL_ADDRESS", "")),
        "email_address": os.environ.get("EMAIL_ADDRESS", ""),
        "email_password": os.environ.get("EMAIL_PASSWORD", ""),
        "smtp_server": os.environ.get("SMTP_SERVER", "smtp.gmail.com"),
        "smtp_port": int(os.environ.get("SMTP_PORT", "587")),
        # Enhanced alerts for remote setup
        "alert_on_trade_fill": True,
        "alert_on_stop_loss": True,
        "alert_on_daily_summary": True,
        "alert_on_errors": True,
        "alert_on_large_moves": True,
        "alert_on_connection_issues": True,  # New: Network issues
        "alert_on_windows_computer_down": True,  # New: Remote computer down
    },
}

# ==============================================================================
# STRATEGY CONFIGURATIONS (unchanged)
# ==============================================================================
STRATEGY_CONFIG = {
    "iron_condor": {
        "enabled": True,
        "delta_short": 0.15,
        "delta_long": 0.05,
        "min_credit": 0.30,
        "days_to_expiry": [0, 1, 2],
        "entry_time": "10:00",
        "exit_time": "15:30",
        "max_loss_percent": 200,
    },
    "credit_spread": {
        "enabled": True,
        "spread_width": 5,
        "delta_short": 0.20,
        "min_credit": 0.25,
        "trade_direction": "both",
        "entry_conditions": {
            "min_iv_rank": 30,
            "rsi_oversold": 30,
            "rsi_overbought": 70,
        },
    },
    "zero_dte_scalping": {
        "enabled": True,
        "entry_window": ["09:45", "11:00"],
        "scalp_target": 0.10,
        "max_contracts": 5,
        "momentum_period": 5,
        "min_volume": 500,
        "use_limit_orders": True,
    },
}

# ==============================================================================
# DATABASE AND LOGGING (unchanged)
# ==============================================================================
DATABASE_CONFIG = {
    "db_path": "data/spyder.db",
    "backup_enabled": True,
    "backup_interval_hours": 24,
    "backup_retention_days": 30,
}

LOGGING_CONFIG = {
    "log_level": os.environ.get("LOG_LEVEL", "INFO"),
    "log_to_file": True,
    "log_file_path": "logs/spyder_remote_tws.log",  # Different log file
    "log_rotation": "daily",
    "log_retention_days": 30,
    "log_format": "%(asctime)s - %(name)s - %(levelname)s - [REMOTE-TWS] %(message)s",
}

SYSTEM_CONFIG = {
    "mode": (
        "production"
        if os.environ.get("DEBUG_MODE", "False").lower() == "false"
        else "development"
    ),
    "debug": os.environ.get("DEBUG_MODE", "False").lower() == "true",
    "performance_monitoring": True,
    "health_check_interval": 300,
    "auto_restart_on_error": False,
    "max_memory_usage_mb": 2048,
    "remote_tws_monitoring": True,  # New: Monitor remote connection
}


# ==============================================================================
# HELPER FUNCTIONS FOR REMOTE TWS
# ==============================================================================
def get_active_config():
    """Get configuration for active trading mode with remote TWS settings"""
    # For remote TWS, we don't need auth credentials in the same way
    # TWS handles authentication on the Windows computer

    paper_config = IB_CONFIG["gateway"]["paper"]
    live_config = IB_CONFIG["gateway"]["live"]

    # Default to paper for initial setup
    mode = os.environ.get("TRADING_MODE", "paper")

    if mode == "paper":
        return {
            "host": paper_config["host"],
            "port": paper_config["port"],
            "clientId": paper_config["clientId"],
            "mode": "paper",
            "connection_type": "remote_tws",
            "remote_ip": "192.168.1.4",
        }
    else:
        return {
            "host": live_config["host"],
            "port": live_config["port"],
            "clientId": live_config["clientId"],
            "mode": "live",
            "connection_type": "remote_tws",
            "remote_ip": "192.168.1.4",
        }


def validate_remote_connection():
    """Validate remote TWS connection"""
    import socket
    import time

    config = get_active_config()
    host = config["host"]
    port = config["port"]

    try:
        # Test TCP connectivity
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(10)
        result = sock.connect_ex((host, port))
        sock.close()

        if result == 0:
            return True, f"Connection to {host}:{port} successful"
        else:
            return False, f"Cannot connect to {host}:{port} (error: {result})"

    except Exception as e:
        return False, f"Connection test failed: {str(e)}"


# Print configuration status on import
if __name__ != "__main__":
    print("🔗 SPYDER Remote TWS Configuration Loaded")
    print(f"   Windows Computer: 192.168.1.4")
    print(f"   Paper Port: 7497 | Live Port: 7496")
    print(f"   Connection Type: remote_tws")

if __name__ == "__main__":
    # Test the configuration when run directly
    success, message = validate_remote_connection()
    print(f"Connection Test: {'✅' if success else '❌'} {message}")

# MAESTRO FIX: Race condition delay (Claude's proven solution)
PROVEN_RACE_CONDITION_DELAY = 1.0  # Critical delay for API handshake stabilization

# MAESTRO FIX: Enhanced connection settings (All research reports)
ENHANCED_CONNECTION_CONFIG = {
    "request_timeout": 30.0,        # Extended from 4s default
    "connection_timeout": 15.0,     # Generous handshake timeout
    "use_readonly_mode": True,      # Bypass reqExecutions timeout
    "disable_order_download": True, # Prevent startup sync issues
    "enable_tcp_nodelay": True,     # Copilot's optimization
    "max_retries": 5,
    "retry_delay": 2.0,
    "apply_race_condition_delay": True
}
